// Auto-generated by html2cpp
// (c) Vladislav Kalugin, 2020

#include <string.h>

String html_css = "p, h1, h2, h3, h4, h5, h6 { color: white; } a { color: white; } body { background-color: black; font-size: 14pt; } .wrapper { margin: auto; width: 100%; max-width: 1000px; } .center { text-align: center; } input { height: 20px; width: 200px; } .submit { width: 200px; height: 40px; background: transparent; color: white; border: 2px solid white; border-radius: 3px; font-size: 12pt; }";

