// Auto-generated by html2cpp
// (c) Vladislav Kalugin, 2020

#include <string.h>

String html_config = "<!DOCTYPE html><html lang=en> <head><meta charset=UTF-8><meta name=viewport content=\"width=device-width, initial-scale=1.0\"><link rel=stylesheet href=style.css><title>ESP-IOT конфиг</title></head> <body> <div class=wrapper> <form action=/api/configure method=POST> <h2 class=center>Настройки Wi-Fi</h2><br> <p> Имя сети: <br> <input type=text name=SSID placeholder=MyNet> <br> Пароль WPA2: <br> <input type=password name=PASS placeholder=********> <br> Домен: <br> <input type=text name=HOST placeholder=iot_relay><br><br> </p> <h2 class=center>Привязка</h2> <p> Ключ устройства: <br> <input type=password name=KEY placeholder=oiajrf938rth49g34fwfe><br><br> <input type=submit value=Save class=submit> <br> </p> <hr> <p>(c) Владислав Калугин<br>https://kaluginvlad.com</p> </form> </div> </body> </html>";

